[profile.default]
src = 'contracts'
out = 'out'
libs = ["lib"]
remappings = [
    '@openzeppelin=lib/openzeppelin-contracts',
    '@chainlink=lib/chainlink',
]
[rpc_endpoints]
mainnet = "${MAINNET_RPC_URL}"