export const steps = {
  JOIN: 'JOIN',
  PROVIDE_IDENTIFER: 'PROVIDE_IDENTIFER',
  PARTICIPANT_STATUS: 'PARTICIPANT_STATUS',
  PICK_WINNERS: 'PICK_WINNERS',
  CANCEL_UPKEEP: 'CANCEL_UPKEEP',
  WITHDRAW: 'WITHDRAW',
  WITHDRAW_KEEPER: 'WITHDRAW_KEEPER'
}

export const participantStatus = {
  LOST: 'LOST',
  WON_UNCLAIMED: 'WON_UNCLAIMED',
  WON_CLAIMED: 'WON_CLAIMED'
}
