export const steps = {
  JOIN: 'JOIN',
  PROVIDE_IDENTIFER: 'PROVIDE_IDENTIFER',
  PARTICIPANT_STATUS: 'PARTICIPANT_STATUS',
  PICK_WINNERS: 'PICK_WINNERS',
  WITHDRAW: 'WITHDRAW'
}

export const participantStatus = {
  LOST: 'LOST',
  WON_UNCLAIMED: 'WON_UNCLAIMED',
  WON_CLAIMED: 'WON_CLAIMED'
}
