[profile.default]
src = 'src'
out = 'out'
libs = ["lib"]
fs_permissions = [{ access = "read", path = "./"}]

[rpc_endpoints]
mainnet = "${MAINNET_RPC_URL}"
goerli = "${GOERLI_RPC_URL}"
local = "${LOCAL_RPC_URL}"